apiVersion: v1
kind: Namespace
metadata:
  name: coxswain-cni-probe
  labels:
    app.kubernetes.io/name: coxswain-cni-probe
    app.kubernetes.io/part-of: coxswain
    coxswain.io/probe-namespace: "true"
