apiVersion: v1
kind: ServiceAccount
metadata:
  name: coxswain-cni-probe
  namespace: coxswain-cni-probe
  labels:
    app.kubernetes.io/name: coxswain-cni-probe
    app.kubernetes.io/part-of: coxswain
